name: value_notifier_ext
description: Helpful utilities for Flutter's ValueNotifier
version: 0.0.9
homepage: https://github.com/tim-smart/value_notifier_ext

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
